---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: client
  namespace: flux-system
spec:
  image: mariansmolii/devlinks-client
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: server
  namespace: flux-system
spec:
  image: mariansmolii/devlinks-server
  interval: 5m
