apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devlinks
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/mariansmolii/devlinks
  secretRef:
    name: git-credentials
