---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: client
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: client
  filterTags:
    pattern: "[a-f0-9]+-(?P<ts>[0-9]+)"
    extract: "$ts"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: server
  filterTags:
    pattern: "[a-f0-9]+-(?P<ts>[0-9]+)"
    extract: "$ts"
  policy:
    numerical:
      order: asc
