apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets-gcpsm
spec:
  provider:
    gcpsm:
      projectID: devlinks-458113
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
