apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-devlinks
  namespace: devlinks
spec:
  acme:
    email: "smoliimarian.dev@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
