---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCEPCNO6a8HQ/YpvF8Bw+slnNPCXUp1Z8k0A2J/fBO1m+Mg/OC1m1FlMBx7rv5+P5UbLzmEhVnj+8q3n6HRakkaMfidvONmXmn/hZzy7xaO33R37ZjZSeBCdXCezuEGOhFDey+vCulMVhxu5DgGycLNQ8YP14jA9hwxaVCSUOT8pUjtDOCcc4NGhJdRBPfho0tle3dzHyxlIFg3v6F9s30rByxL/YEz9Z3CcrxGXmpKgV/LhzeNwMPm45EfwfE1vmywQHR+xxJ5Bgb/HhX7BHAdgwzp0Jn1wAs07Wx595DLwu8oRgXQmyNiDuR5V+VntrIMVRUkKx5xTuhqJj31hC36wCYOh+jxZW7/7GuiNHAtHDJvcE93kGoRfSuIUleRLDuvDllm+OYspx4HvKXZ94MEcdha7S+beJRVnNvC+u0aQgb17+ETcoofIjXsD0fiqbtNZyUkXkuhi6Aume+EXHRZukfCK9859Uzx0HwSaeicvzCCSXNLBh5kdIEXZPGjYPIgRO3O2P+C5tOURy8gEGUk7J6k6hJJLkbkiiDqe8llp4mYRUP37AYziOBHPF+BRtJi79gbyEK0w1qNueEI5120hxTFy7ArR9UfwSFWZDcVcwp/2Vne8PdgkugRKr/w5kcWUqporW1LEQAwxaH7qw4/JdVzxczdbPDG3GZ+L4OWlv1VuTnEeu2uQW4OIJsGsb7N4P9u/cO2Gr92th4woVZ2kTkNLVeEF9S9jwnv5blW+0IjLya+n6kc
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
