---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: devlinks
spec:
  encryptedData:
    api-token: AgCQ/8bbe48Xu5eRPZkkNqjI1seeUXNlcOODxzbNN/Zb4O7US7833IZ3B9dREECTkazKZYU3nKs1cf8udy9hWSsm//FlyLlZgPxVR8wgFxV8r+K76kEqq/490SRGyyArLCQnMfA6zOISLze3SFZUU9XoT9mIHXhyivzTWQ8UbBs0HsqT2DKhxhy16PUrFE1P3V2xykaWHCZwnpWz3zvgZfmcn6GUibEiqmjLY77HYsTf0stLJSacf6wcPPLzoKwJieDa9hZtudXQyPHEAu/Z0kpD6/w4aPFaSnDYkzeCnwlyuOe98dODqjYLjUzNlKywaS+u+FxYt8L+CIEQ1HpG//O51PZ0w/hl1Rp/Oo0ae4NeRvGGbIOehnLYBEJ5BTw4DdbQBx/EqnHs1YYSK7fhr21PEzgiRt81N3TTkdZQS9HkfXCid1H8jLqTga/FzioVBfy9ElHYO/of0v0b0u1Z6RiODPGvfty12fRDskAe5dNKCb0G+GM1+pLhE0RjjNynwbGsphpG43TZ5vtRiFp5SfkXuu50qvXMqfSc6ZgsjHH0O03InYq3EDeZh9mk2X+9WwkIj6pEaqD6uEvQCX2sv9srnTbzmuOUmsm5X4hdsf9noNqzttvBxK4NQFjimJH55ft5d8evx8b5/S9+y5y7dcSE1dcwPcMILJ66CcdC1ICzsByH1hUCHVegXG/aKA6D/DuQAPZ9q6oMHIX/US4fGv44nikBw/8OX0AHcbBmKOoQHk7a6oZTh4Zl/6Tp5ozUqCsW7dT3gx7W3A==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: devlinks
    type: Opaque
