apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=70.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    fullnameOverride: prometheus
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 11d
        resource:
          requests:
            cpu: 200m
            memory: 512Mi
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
    grafana:
      fullnameOverride: grafana
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: monitoring
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc.cluster.local
          access: proxy
