---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBIr4GcOAFDLOFSVR6nFIdN1RBNrtz6NhwowHgvewZgBE+xJo3ED90G805EfqBBtLCWannz5yaTL6FVgFQtrQPIeroKDe76VfelvBD83V9iIKOPfZ+GPtGEsvt/Pzk7ShixjzmVzphZ4wZrmdLil0m4drJhLXyrkisw3+eG4MB593afIUy1D5MJpoSJydX4kOYprSMH/DqdfA7FynIRrmHhZQEXHGrKMGVyS4368mmW5W1oairHhNr7PcFTfw0TJTwb+W/AQ5OilO9GNZe6Jllkp6+VkKyRZM5hr4mw5azLBbyi5If+k6/StZV87FLW2BD9HVSzLtAZxWNiChIZIETNzQ0cgYiw5A2ejFNY0w3bxcbrtGk4RXAlhqR+dYP5fi8fLp/i7pWF23AHvvCfo0gRnwotSq1VnrXooQ7tQA5oxng5SP1buiG37J9IgNLYdm+lVjU09EShcb6C/WN2okPKyERzQmHeuxmCPHqrJcKfh/iM+AI4Dp2EklE5fYu0MH8bE6EhRy+rLe+m0zKkCio3tIHgqWrHYaCfnK2ygX+WHpNa+/PHtMrI6v1463isYF3IFq+jzMeFJLAknjCZRHNbBzQCtcHdNdY7WgenpXmp/XfYnMKpRkuR3otrRD8h/qOHWbbBdokI1PVVQZSGcdct6iqmMpGn0D90FCBlV5au4baN9gamUmffrphgNyo0vGWPO432GNKljFUl
    admin-user: AgAP9k5ew4u3/lDyjghQRpNEJX2VbzS8XVQ1VsVL1ISJaVuO0eIQ3SCoMTjnP/IVu9qvsEKmiAlzaST0h915UsMP2R9s/dtLeezlIMpGmczVuJ8BuIaFTbJlDkYTj5xpZDiS4496s3WdwLdeK1/sHn8Dx2jLdVtAbQHCy368vUlgyxQA2FpjZ6bp0UqIV8X/QzrThMTQwz8HTRFhFbVbRoFLcBddMkDYxMNHu2muOD+8CEN5xsZSuBjME0sy0rvtsKPGFyY3Ls4gvmRpcnT80s1R/pVrWVT/seidxK65K7iy6Xgzr61mZpm8NI//d3lVFbz00SqNRVS3/7dsEKh1r/czaHgVng9zoirXjW6LW77S3OgAGvGlKb59SY9HZqe4ranY0KZ2bOCn6tDrBIf7Ywo7mmPpV9+X0JcWrticzLtxp3gbVNfRRg48Lj7gvebEpl83r2SxAF6hKEuaBVLKo8HA2zGJOOvKfD4uEg0lYIrIeRk0xX13oIwcy6y9hVn3tQ8U7mVNtOSxWPGRR2MoHteetCQhdvyZYBKISaLn3JDHK3moYErVbNkvN6YegN2hMbQrdOGXe23LSptsX3USWA2v2ALJ7Yz5wTcS7mOojzy4GHQoVMGomkUEXyHjwJVBzXKAa/ZBRL42TssnN9ckNUgIXBSnR3iWbKQIZX0m0vpRDz0gNsTLm6dEtQcxom5C66tXkImvmkw=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
