---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAPr3lBtjMe7YzuPhZ0xcaLdoOB7U+a85JCXO9BpnOv2WRBBbTEX6Dgyj4s6bo3YSVlwT/297FXiJs3o4uhysysfVqOToH954/XtZv7uoPkTqSZdEftsw79/0UplDOeMsrAwOg7Qy3HJj6jg4eU6IVNCny5Q6ZXSB9HKZjmRbGUfLjwj45r7iqVZnx9Y5rd20hM9l5VnjgjQkE8C/q+6K6n0DqN3hs+E8wtZqgCztkr1WxHEJh6PDfXk8DSxsUKB7sP+wUqcOHrDT7ruw4p9nj8zH8jSN2cLv9u0STQVEUdtdea0OCRasL/Wh+LuGDzlHNFamt3kj4Th3GWrKkJCVpYaC1xIfijVcskPtldBAZTFvDmqCS9iATfcHtJJX4hVFvrdoH2AwNwYuWPOF1AIsGvZ6t3LUcqkolSZG+ToNv5RzK1sFfzrCoD62sLs3zeF0/9JKbKLu706KxhcfPVwuC36t5x1u90UGxfysPxRD+qRdITD+czOuCbLorGiYNAh1g0vhAnvgm0zphIkUysgYeWVG2YVaTv497uo+UgIbUQibWEmdfA5AeRSU+liekMwjTxSqdPiG0qGAvwlJbwX0AiEARIwjiFRlfN48un2T/XJW3vhdv0PFGXHNAoISKCPSPwV+dYcf+pM8siJBIHVxb9sm4FNQLi5S4AojuVQjV/mnv7lxWgkoFiLSMgRiYdTD5F+ACuxR6+kzSU
    admin-user: AgAXIHIlhimdRBHTn9m9Tb+e4iM79UKoVMkbaWCednhoE1TsnsGHVdZ2vz0vStBLW1fk6qgAUzi5cecA5QByC4TZb4RuiglsnXQxImOcCxnZ6OunR+2AQMFdanAW4QjxYbb8SJxTTStpfhkrp5IxJdNv//T8UYZmLtwtAMJBaU7sR4R5jGxYK2bMZWh6Km9ZcjTyu2QckvQVkaf+Bke9lgfgSwnkGIqxaoJqgwbaf74hPS6QS9z/Sva6oyuJCjjGwG+gmSJixKjOYvd0jmobABZvy0QFMhriM8Z2o1zoyBTDEBPXVFhlkZJSDmH6GJZfgugsa3XMFIyrAmhwKVmFYAobuSE2SZ7/8rocvJqPB4yiAtGg/NZjSjq3ZCAZ/cpv/Jt7Fk3rPxJyMsZ2HNSmMYLqKfWGEV/zx5YWTSgd+IdkIf5mVliFJi1aIvxnJxlVVLSmuBMhBdX6HXQ26rJSSXSHq2AT0eCWBaBlH4QOoWURwHrI5pNbnmDVnR0RrCccpI8k6GlDEoB3WmEOgNWnfPz0lFkHC0Pcim4SS7bGALzMXS2L0x4cqn0LiifI3TAS3Yr/u17N0Ch7GZhxZieUmWJTMAawyqtMgfONj257JuNkFU00kK+h2CWV1WrXqSsIs9dq+nDK7ByOHuevM3sPorMN7mD+w26zVehujOqDlBIyZblXUxMk3S1dhOLM4P74e3PSutJonfg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
