---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlinks-client
  namespace: devlinks
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      volumes:
        - name: devlinks-nginx-config
          configMap:
            name: devlinks-cm
      containers:
        - name: client
          image: mariansmolii/devlinks-client:54f7b3814072595e0cf13f29be44767ddaba75dc-75 # {"$imagepolicy": "flux-system:client"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: devlinks-nginx-config
      nodeSelector:
        app: client
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: devlinks
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30007
