---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devlinks-cm
  namespace: devlinks
data:
  nginx.conf: |
    server {
        listen 80;
        server_name devlinks.uk;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri /index.html;
        }

        error_page 404 /index.html; 
    }
