apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devlinks-ingress
  namespace: devlinks
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: devlinks.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-svc
                port:
                  number: 80
    - host: backend.devlinks.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-svc
                port:
                  number: 1111
