---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/base/database
  dependsOn:
    - name: infra-controllers
  prune: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: devlinks
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: server
  namespace: flux-system
spec:
  path: ./kubernetes/apps/base/server
  dependsOn:
    - name: infra-controllers
    - name: database
  prune: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: devlinks
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: client
  namespace: flux-system
spec:
  path: ./kubernetes/apps/base/client
  dependsOn:
    - name: infra-controllers
    - name: server
  prune: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: devlinks
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  path: ./kubernetes/apps/base/ingress
  dependsOn:
    - name: infra-controllers
    - name: server
    - name: client
  prune: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: devlinks
  wait: true
