apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlinks-client
  namespace: devlinks
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      volumes:
        - name: devlinks-nginx-config
          configMap:
            name: devlinks-cm
      containers:
        - name: client
          image: mariansmolii/devlinks-client:db780a48fbe0fc65fc3bc773b4e591a4fbf2beed-122 # {"$imagepolicy": "flux-system:client"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: devlinks-nginx-config
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        app: client
