apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: ">=0.16.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 12h
  values:
    installCRDs: true
    serviceAccount:
      create: false
