apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: devlinks
spec:
  interval: 30m
  releaseName: mongodb
  chartRef:
    kind: OCIRepository
    name: bitnami
    namespace: flux-system
  values:
    fullnameOverride: "mongodb"
    architecture: replicaset
    auth:
      enabled: true
      rootUser: root
      usernames: [myuser]
      databases: [devlinks]
      existingSecret: "mongodb-secrets"
    replicaCount: 3
    persistence:
      enabled: true
      storageClass: "standard"
      size: 10Gi
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    nodeSelector:
      app: db
