apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secrets
  namespace: devlinks
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-gcpsm
  target:
    name: mongodb-secrets
    creationPolicy: Owner
  data:
    - secretKey: mongodb-metrics-password
      remoteRef:
        key: mongodb-metrics-password
    - secretKey: mongodb-passwords
      remoteRef:
        key: mongodb-passwords
    - secretKey: mongodb-replica-set-key
      remoteRef:
        key: mongodb-replica-set-key
    - secretKey: mongodb-root-password
      remoteRef:
        key: mongodb-root-password
