apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: mongodb-grafana-dashboard
    namespace: monitoring
    files:
      - dashboards/mongodb.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: ingress-nginx-grafana-dashboard
    namespace: monitoring
    files:
      - dashboards/ingress-nginx.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: default-dashboards
    namespace: monitoring
    files:
      - dashboards/node-exporter-aix.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: flux-grafana-dashboards
    files:
      - dashboards/flux-control-plane.json
      - dashboards/flux-cluster.json
      - dashboards/flux-logs.json
    options:
      labels:
        grafana_dashboard: "1"
