apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: mongodb-grafana-dashboard
    namespace: monitoring
    files:
      - dashboards/mongodb.json
    options:
      labels:
        grafana_dashboard: "1"
