apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: ">=1.14.5"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    sources:
      - ingress
    provider:
      name: cloudflare
    domainFilters: ["devlinks.uk"]
    txt-prefix: "devlinks-txt"
    policy: sync
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: apiKey
