apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-gcpsm
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: external-dns-token
