apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: ">=6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
