apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlinks-server
  namespace: devlinks
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: mariansmolii/devlinks-server:b38e6b60f0ca7e69c9200e918711db73ee515764-115 # {"$imagepolicy": "flux-system:server"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1111
          envFrom:
            - secretRef:
                name: server-secrets
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      nodeSelector:
        app: server
