---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-secrets
  namespace: devlinks
spec:
  encryptedData:
    db_host: AgATdMF+r2yMaXobo17K1vz7ob5Ej0sjB/I+HPzW3H3iy1e0vZvwFi1e6oaA5ro428pJKBgaAq9Jfs/G6/5E+Crldwu85RAuKmO05gxiTTbvpcJE6z2ZhR7bfCCkNGA2ltinZ/eYs6yortSk2pTRbUi/rBZbUBYmKRSxyMzUS3CA81HqJX8OtU3bOgvutnrIaikwRdMLunHqK6SFrrsPZOMJkBm8qMwrcTnryLhSxFvUAWHayYRgy4RZDFHQHy9wZYX6ONszGF9K/DfVle+82R6YHyQGSYcEMr56oEPhlU9XZQ8JaqJvq5gWpt5xrtzWhD6wvF0xbsQZodPGi5MOilD7m3F5Wy6++LGpQTAy1BPg22+8CgoZ85SCtl4YpP9ZLrmbkL0i3Pp6tSU1GpcE3DTqmNBua0osMUr5lPTVwbfCh2C1QRrbx0s3gW+v9x1tZ0SNt9y+JvQ4/E8HvyAcjPtsSA/AjhLzl96UDNvXhxX4TdgjtCFS0vRvUu6f75Vqn0Ef3aQ5dQhH0mQj0xIuy4IMaTU1IUaTXpwbrUjTHB8u2nFRjBJcosu+OeFTvsDVcz2DksvciqxpUbPWeh5n2H7dVUzR4Bw+G4StBISs1iS6TmrhNTGwgqhibtf9ExOtub8gl9h17ifuePdssoCu4wlzU3anmEN3ML9cimIQcRjMHGTbtLrvT1wKPoO7M7avUG7ATwUmEIt41zopXexnh1/8YjRWEal8iN68lweCSrIQ0tQz3qG+w3EmTHCa73dE6xYoXRl1lQ67FXAPb6W7yvW+z+LJ3TpX/DA5tmfSMiN54WKbiQr9Wj1cI04=
    jwt_secret: AgBIUvZ0PDqjyOAdNVORB914eaXf4jRi1NlehHm2CFCREHKjm5vJqMfQy7tXmlrMcxwiJplFzI/WIOEed0B+7cC7IHw8Nvfv/7aqVbWriOgnNSw0ljZ/aXU2fxSGw0asAiw+QfGtY7DbHqHyw/7nvLM8O9iunL2FpIjSVEH3m1sX6Sn4fBUSrmGydCiH7jpUXOuxFDfsZcuEaGELFwETjLb7bUnFf64XpA51DiA2nd3v+Gt5CiktuFBQIbYcBeYHnhwZ4z7kAKMadCJ1c84T+4jf4W0+irMTOCwUXOKyNNBopFxcZOLUlyvI+1ke8c9tAkL79/cZhMhw6YMmG+jtB38rCofTKZXf5h7IacODLjnxWsl1ra3hAiWWDrvFa7dD6B23fAn3yiZDfvBTfw8BX2/0dL3O9knjcinYVThB76IeY5mdeC/Fp3ydzjKsd/l+9ctWULpiyeSqMPizc4bIwnFZDC6bqT8PU3JI8et5nyPLjgrvg36iANkjRsseexcc5beZSpz5P8P9EvtZ0XFUeybK8GoUcStKLhdFBouoefHgXOgHMTttibJJCmJaHXtY83z23jAjinHtFcB9kTEOeRjAzHcKOnOvEask3792EUSCHAqRrsf7a/f+ODxvgafnSl2z2zRWxUHYo37+kwNQcfJNKwHuV8zMTV8IBDnYrKiPzQ7f+sNSheWlPJRiO4yK8iExqDTap9NFSEJiGkEZKiGWPVn3a1c=
  template:
    metadata:
      creationTimestamp: null
      name: server-secrets
      namespace: devlinks
    type: Opaque
