apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-secrets
  namespace: devlinks
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-gcpsm
  target:
    name: server-secrets
    creationPolicy: Owner
  data:
    - secretKey: PORT
      remoteRef:
        key: port
    - secretKey: JWT_SECRET
      remoteRef:
        key: jwt_secret
    - secretKey: DB_HOST
      remoteRef:
        key: db_host
    - secretKey: CLOUDINARY_API_KEY
      remoteRef:
        key: cloudinary_api_key
    - secretKey: CLOUDINARY_API_SECRET
      remoteRef:
        key: cloudinary_api_secret
    - secretKey: CLOUDINARY_CLOUD_NAME
      remoteRef:
        key: cloudinary_cloud_name
    - secretKey: CLOUDINARY_FOLDER_NAME
      remoteRef:
        key: cloudinary_folder_name
