---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-secrets
  namespace: devlinks
spec:
  encryptedData:
    db_host: AgAFJLQa6/aiAl68cLJ3m3+gXdM/AESZxFaE68ckT9tKX8jT3BGPdHge8I4HwPOxuCevvNy4hAQuAnkIwLPmqKvJIT+/079vy0zkQsZP0Wg1idsQ0RHGAa3/Xy42DOsxSSJH7bgxThqvM4aPVOOp5nrTSy9gTHTp//ZD966oH1eegZHNSVHxhmk6GEWpPGxQYJ0SGOvA/XmVHGKjPOPXdg8ZFCbfUvWt2LjzwGaq95PVe4sIF1d7ag8aItbVqmlvfT5WDizqUlhqxtXRNZpWde8HSstxdMvCrrm+G1ESQVmdqSoKYn9dOgTj3s5sB+mpvmtVgFNC+SraquBqUdHBQg3cNxX1MQB152oESyuTXCHZOLRVi29+bLjP8ARcJ4PNvBkCCONWcXKcvcftVz5HYbZo//L8u10a6EYU6OgtufbDlwctaKgBYn5i0ocR7bVa4sDq1Bp+XUkIMZtoUisPl25yJKCuNHk+dmcIl7a9x8ZTWM3H/fFPX1+zFOOEXYXOYPQPhsJ4RP6EME+jbzs40id7hXOsJ1F+ezntUhH7E5CT3Hsvcs5J3G7q6IAQDZKvyIFUkHZLFE80H6jK138rlnZwXUM3zxM0w4lWCfc4mHvq6VAavJN/xWm+IugDFgsBSP4+/HFjY9KiN7pYjgkiOMGvQ6vF4r5RKz0sTdKZJWUeri9wKo4btnWp3vPoMBoGVXlV1KudrN+SRM8iAOrZ1Lt4tc6+4f7CyxFd/ExqqtrSjwcC/LhIS66nTpc7EXaJMnIHOvoGGHsOHX25R6AD+SuVtluauQ/opMCc/kJzusxE+PhnQ+HcxeQAFGg=
    jwt_secret: AgASpx1xzyGpkwfgeB522ac3XfSHlvaaQOhTIOZWXsPMSh9/7gi6pXuqIoDM+M0igK9tlLFsWXrBwVNsv4AQ95O4ha/4S2yL/Ycji64plvjPXAuE+q/8iklZvRDq05rsFmx567+JBRf2z8/GfaLnR4fHVU2bADVHbDHqOYBOljT2YScjc6rOSVQMjcVybee49wvzksyYYxBy+nQssXvwlvE1i7FwRy1bOulRf6CdVg6ZdtPILNWPK/uDzwGtlDyiYxvdegVjFlwaXrBkWZfbJNl9W1M2VEe0eUdCBILtcpFbxgBOT9dGj5ODkQEjt9rQw465Hxst+htqgQ0ShWqvFGbIwebEaBmTpS6yEZOUV3nUc6CSax24cbWcDA2Sak7fMHxN4MjgWVM1GcbdBo8rRlqNHPbGpuypFvjJSHqVvARxUs1YKcLrcBFSkhT7/yynaHoMIDOUPWyv5/o3gb5SEf8/fQag8mjIl+6xvEPMgBCxH/UTjH+0KPmsiQg+vvSQVw8k4bJiXsm/Jawi18V6QRfw2soVAma4TTBm+VfYrMafULd6PmehIhBDZuN3GSq4d3Evf85TIboDvgrLcUM8Pb2wYmNNd+bCnNfOTgLtIiSXOoiSzPYAf9/mjMoTw4r8nI9dbyLVftv90FXr7s6nd4LXk2O7pQbO6O/xJi8sCgb36x4UF4xzGQQIQ/pQ867OyUzhIEERjV8U/LoudjIJktf86Kua/Ro=
  template:
    metadata:
      creationTimestamp: null
      name: server-secrets
      namespace: devlinks
    type: Opaque
