apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: devlinks
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1111
      targetPort: 1111
